In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=pd.read_excel("C:\\Data Analytics\\EDA\\EDA PROJECTS\\manufacturing_data (2).xlsx")

In [5]:
df.head()

,Date,Machine_ID,Machine_Type,Shift,Operator,Production_Units,Downtime_Min,Downtime_Reason,Defects,Defect_Type,Raw_Material_Used,Energy_Consumption,Temperature,Humidity,Maintenance_Type,Maintenance_Cost,Production_Target,Cycle_Time,Rework_Units,Inventory_Level
0,2024-01-01,M2,Semi-Auto,Night,B,436,47,Maintenance,8,Dent,575,126,51,27,Corrective,3482,549,27,5,1436
1,2024-01-02,M1,Automatic,Evening,E,565,11,Maintenance,3,Scratch,589,155,51,29,Corrective,5871,519,26,5,1526
2,2024-01-03,M4,Semi-Auto,Night,E,562,15,Breakdown,7,Dent,586,116,43,25,Preventive,4256,617,32,1,1301
3,2024-01-04,M5,Semi-Auto,Night,B,478,9,Breakdown,8,Dent,595,142,48,38,Preventive,3142,614,37,3,1505
4,2024-01-05,M1,Semi-Auto,Night,B,427,58,Setup,2,Crack,579,137,54,25,Preventive,5614,624,36,3,1219

In [6]:
df.tail()

,Date,Machine_ID,Machine_Type,Shift,Operator,Production_Units,Downtime_Min,Downtime_Reason,Defects,Defect_Type,Raw_Material_Used,Energy_Consumption,Temperature,Humidity,Maintenance_Type,Maintenance_Cost,Production_Target,Cycle_Time,Rework_Units,Inventory_Level
4995,2024-09-07,M3,Automatic,Night,B,410,34,Setup,12,Alignment,613,113,40,40,Corrective,4275,600,27,6,1299
4996,2024-09-08,M1,Automatic,Night,B,485,26,Setup,1,Crack,632,134,55,36,Preventive,4565,502,40,1,1393
4997,2024-09-09,M5,Automatic,Evening,C,460,50,Breakdown,6,Dent,641,145,48,27,Corrective,3575,600,33,4,1272
4998,2024-09-10,M3,Semi-Auto,Night,C,470,11,Maintenance,3,Scratch,567,123,45,26,Preventive,2322,627,40,4,1517
4999,2024-09-11,M1,Semi-Auto,Day,B,451,49,Setup,4,Scratch,596,152,43,39,Preventive,2553,578,37,4,1436

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                5000 non-null   str
 1   Machine_ID          5000 non-null   str
 2   Machine_Type        5000 non-null   str
 3   Shift               5000 non-null   str
 4   Operator            5000 non-null   str
 5   Production_Units    5000 non-null   int64
 6   Downtime_Min        5000 non-null   int64
 7   Downtime_Reason     5000 non-null   str
 8   Defects             5000 non-null   int64
 9   Defect_Type         5000 non-null   str
 10  Raw_Material_Used   5000 non-null   int64
 11  Energy_Consumption  5000 non-null   int64
 12  Temperature         5000 non-null   int64
 13  Humidity            5000 non-null   int64
 14  Maintenance_Type    5000 non-null   str
 15  Maintenance_Cost    5000 non-null   int64
 16  Production_Target   5000 non-null   int64
 17  Cycle_Time          5000 non-null   int64
 18  Rework_Units        5000 non-null   int64
 19  Inventory_Level     5000 non-null   int64
dtypes: int64(12), str(8)
memory usage: 781.4 KB

In [8]:
df.describe()

,Production_Units,Downtime_Min,Defects,Raw_Material_Used,Energy_Consumption,Temperature,Humidity,Maintenance_Cost,Production_Target,Cycle_Time,Rework_Units,Inventory_Level
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000
mean,501.189800,32.284600,6.531200,600.009800,135.146600,47.512600,32.51940,3728.265800,575.458400,32.522600,3.52560,1401.143800
std,58.460689,16.275656,3.459049,29.129645,14.764468,4.598094,4.57443,1296.261263,43.138401,4.615339,1.70503,114.793304
min,400.000000,5.000000,1.000000,550.000000,110.000000,40.000000,25.00000,1500.000000,500.000000,25.000000,1.00000,1200.000000
25%,450.000000,18.000000,4.000000,575.000000,122.000000,44.000000,29.00000,2630.750000,539.000000,29.000000,2.00000,1301.000000
50%,502.000000,32.000000,7.000000,600.000000,135.000000,47.000000,32.00000,3696.000000,576.000000,33.000000,4.00000,1402.000000
75%,552.000000,47.000000,10.000000,625.000000,148.000000,52.000000,36.00000,4849.000000,612.000000,37.000000,5.00000,1501.000000
max,600.000000,60.000000,12.000000,650.000000,160.000000,55.000000,40.00000,6000.000000,650.000000,40.000000,6.00000,1600.000000

In [9]:
df.isnull()

,Date,Machine_ID,Machine_Type,Shift,Operator,Production_Units,Downtime_Min,Downtime_Reason,Defects,Defect_Type,Raw_Material_Used,Energy_Consumption,Temperature,Humidity,Maintenance_Type,Maintenance_Cost,Production_Target,Cycle_Time,Rework_Units,Inventory_Level
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df.isnull().sum()

Date                  0
Machine_ID            0
Machine_Type          0
Shift                 0
Operator              0
Production_Units      0
Downtime_Min          0
Downtime_Reason       0
Defects               0
Defect_Type           0
Raw_Material_Used     0
Energy_Consumption    0
Temperature           0
Humidity              0
Maintenance_Type      0
Maintenance_Cost      0
Production_Target     0
Cycle_Time            0
Rework_Units          0
Inventory_Level       0
dtype: int64